#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Please provide exactly two arguments"
    echo "Usage: run-local /path \"php -v\""
    exit 1
fi

docker run -it \
  --rm \
  --name deployer \
  -v "$1":/var/www \
  -w /var/www \
  --platform "linux/amd64" \
  ghcr.io/rechtlogisch/deployer:"${IMAGE_TAG:-latest}" \
  $2
